# AWQ Method configuration
method: "awq"
awq:
  duo_scaling: false

output:
  save_compressed: true
  save_dir_suffix: "-AWQ-W4A16"
quantization:
  num_bits: 4
  weight_type: "int"
  symmetric: true
  group_size: 128
  strategy: "group"
  observer: "mse"
  actorder: null
  targets: ["Linear"]  # Layers to quantize
  ignore:
    - "re:.*embed_tokens"
    - "re:.*norm$"
    - "re:.*layernorm$"
    - "re:model[.]visual.*"
    - "lm_head"
calibration:
  dataset_id: "nielsr/funsd"
  dataset_name: null
  dataset_split: "train"
  num_samples: 64
  max_seq_length: 512
  batch_size: 1
